[package]
name = "vcb-clipboard"
version = "0.1.0"
edition = "2021"

[lib]
name = "vcb_clipboard"
path = "src/lib.rs"

[dependencies]
base64 = "0.22.1"
ndarray = "0.16.1"
anyhow = "1.0.69"
zstd = "0.13.3"
binrw = "0.15.0"
colored = "2.0"